PATH = ''
VERSION = "V.1.4.4"

WINDOW_CHECK = True

CTRL_SIZE_VALUE = 1
CTRL_GRP_VALUE = False

AUTO_RIG_ARM = False
AUTO_RIG_LEG = False
AUTO_RIG_CHEST = False
AUTO_RIG_HEAD = False
AUTO_RIG_STRETCH = False
AUTO_RIG_MIRROR = False 

DICT_MIRROR = {17 : "", 0 : "_L", 6 : "_R", 'stepLeg' : 14, 'stepArm' : 20}

GUIDE_LINE_GRP = 0

AUTO_RIG_LIST_ARM_GUIDE = []
AUTO_RIG_LIST_ARM_GUIDELINE = []
AUTO_RIG_LIST_ARM_JOINT = []

AUTO_RIG_LIST_LEG_GUIDE = []
AUTO_RIG_LIST_LEG_GUIDELINE = []
AUTO_RIG_LIST_LEG_JOINT = []

AUTO_RIG_LIST_CHEST_GUIDE = []
AUTO_RIG_LIST_CHEST_GUIDELINE = []
AUTO_RIG_LIST_CHEST_JOINT = []

AUTO_RIG_LIST_HEAD_GUIDE = []
AUTO_RIG_LIST_HEAD_GUIDELINE = []
AUTO_RIG_LIST_HEAD_JOINT = []

CTRL_CHEST = False
JOINT_HIPS = False

CTRL_IK_CHEST = False
JOINT_IK_CHEST = False

CTRL_FK_CHEST = False
CTRL_FK_NECK = False

CTRL_GENERAL = False



SHAPE = []

CURRENT_SELECTION = []
CURRENT_JOINT = []
CURRENT_SKIN_CLUS = []
CURRENT_SHAPE = []

LABEL_VERTICE_MEMORY = False
LABEL_VERTICE_SELECTED = False

TREE_SKIN_VALUES = []
SKIN_VALUES = []

