WINDOWCHECK = True


CTRLSIZEVALUE = 1
CTRLGRPVALUE = False

AUTORIGARM = False
AUTORIGLEG = False
AUTORIGCHEST = False
AUTORIGHEAD = False
AUTORIGSTRETCH = False
AUTORIGMIRROR = False 

DICTMIRROR = {17 : "", 0 : "_L", 6 : "_R", 'stepLeg' : 14, 'stepArm' : 20}

GUIDELINEGRP = 0

AUTORIGLISTARMGUIDE = []
AUTORIGLISTARMGUIDELINE = []
AUTORIGLISTARMJOINT = []

AUTORIGLISTLEGGUIDE = []
AUTORIGLISTLEGGUIDELINE = []
AUTORIGLISTLEGJOINT = []

AUTORIGLISTCHESTGUIDE = []
AUTORIGLISTCHESTGUIDELINE = []
AUTORIGLISTCHESTJOINT = []

AUTORIGLISTHEADGUIDE = []
AUTORIGLISTHEADGUIDELINE = []
AUTORIGLISTHEADJOINT = []

CTRLCHEST = False
JOINTHIPS = False